version: 2.1
jobs:
  build:
    resource_class: large
    machine:
      image: ubuntu-2004:202010-01
    environment: 
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout # check out the code in the project directory
      - run: docker system info
      - run: docker buildx create --config .circleci/buildkitd.toml --use --name=circleci
      - run: docker buildx bake package --progress=plain
      - store_artifacts:
          path: build/package
          destination: dd-trace-php