version: 2.1
jobs:
  build:
    resource_class: resource_class
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: docker buildx bake package
      - store_artifacts:
          path: build/package
          destination: dd-trace-php